version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - thenativeweb/wolkenkit-dev
  assignees:
  - goloroden
  - yeldiRium
  labels:
  - Dependencies
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: roboter
    versions:
    - 11.6.10
    - 11.6.11
    - 11.6.17
    - 11.6.20
    - 11.6.22
    - 11.6.26
    - 11.6.28
    - 11.6.29
    - 11.6.31
    - 11.6.33
    - 11.6.36
    - 11.6.39
    - 11.6.7
    - 11.6.8
    - 11.6.9
  - dependency-name: assertthat
    versions:
    - 5.2.6
    - 5.2.7
    - 5.2.8
  - dependency-name: semantic-release-configuration
    versions:
    - 2.0.0
  - dependency-name: record-stdstreams
    versions:
    - 3.0.47
  - dependency-name: defekt
    versions:
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
  commit-message:
    prefix: fix
    prefix-development: chore
